import type { GenerationParameters } from "../types/prompt.js";
/** Derived copy of the app version. Root package.json is canonical; this file is regenerated by pnpm version:sync. */
export declare const APP_VERSION = "2.3.4";
/** Stable synthetic connection id for the built-in local llama sidecar. */
export declare const LOCAL_SIDECAR_CONNECTION_ID = "__local_sidecar__";
/** Stable ID for the built-in Professor Mari assistant character. */
export declare const PROFESSOR_MARI_ID = "__professor_mari__";
/** Stable ID for the default OpenRouter free‑tier connection. */
export declare const DEFAULT_CONNECTION_ID = "__default_openrouter__";
/** Default system prompt for AI-backed translation. */
export declare const DEFAULT_TRANSLATION_SYSTEM_PROMPT = "You are a translator. Translate the given text accurately, preserving formatting, markdown, and any special characters like *asterisks* for actions. Output ONLY the translated text, nothing else -- no explanations, no extra commentary.";
/** Default generation parameters for new presets. */
export declare const DEFAULT_GENERATION_PARAMS: GenerationParameters;
/** Maximum file sizes for uploads. */
export declare const MAX_FILE_SIZES: {
    readonly AVATAR: number;
    readonly BACKGROUND: number;
    readonly SPRITE: number;
    readonly CHARACTER_JSON: number;
    readonly LOREBOOK_JSON: number;
    readonly PRESET_JSON: number;
    readonly CHAT_JSONL: number;
};
/** Limits for various entities. */
export declare const LIMITS: {
    /** Max messages to include in context for agents */
    readonly AGENT_CONTEXT_MESSAGES: 20;
    /** Legacy default for the previous global lorebook entry cap. Prefer LOREBOOK_ENTRY_LIMIT_* for new code. */
    readonly MAX_LOREBOOK_ENTRIES: 100;
    /** Default max active entries a single lorebook may contribute per generation. */
    readonly LOREBOOK_ENTRY_LIMIT_DEFAULT: 100;
    /** Minimum configurable active-entry limit for a lorebook. */
    readonly LOREBOOK_ENTRY_LIMIT_MIN: 1;
    /** Maximum configurable active-entry limit for a lorebook. */
    readonly LOREBOOK_ENTRY_LIMIT_MAX: 1000;
    /**
     * Default keyword-scan depth (messages back) for the per-turn lorebook scan
     * when neither the entry nor its lorebook sets one. An explicit per-entry or
     * per-lorebook scanDepth of 0 ("scan all") still scans the full history.
     */
    readonly LOREBOOK_DEFAULT_SCAN_DEPTH: 10;
    /** Default global lorebook token budget per generation. 0 means unlimited when explicitly configured per chat. */
    readonly DEFAULT_LOREBOOK_TOKEN_BUDGET: 8192;
    /**
     * Per-active-character lorebook token budget for a single Noodle refresh. Noodle can batch far
     * more characters into one generation call (up to 100, or uncapped with "All invited") than a
     * normal chat turn (1-2 characters), so it scales its own lorebook budget by active character
     * count instead of reusing DEFAULT_LOREBOOK_TOKEN_BUDGET outright — see NOODLE_LOREBOOK_TOKEN_BUDGET_FLOOR.
     */
    readonly NOODLE_LOREBOOK_TOKEN_BUDGET_PER_ACCOUNT: 400;
    /** Minimum Noodle lorebook token budget even for a single active character. */
    readonly NOODLE_LOREBOOK_TOKEN_BUDGET_FLOOR: 1500;
    /** Hard ceiling for all world/lore context activated by one Noodle refresh. */
    readonly NOODLE_LOREBOOK_TOKEN_BUDGET_MAX: 8192;
    /** Default summary trigger: every N messages */
    readonly SUMMARY_INTERVAL: 50;
    /** Default vectorization: top-K results */
    readonly VECTOR_TOP_K: 10;
    /** Default recent-message window used to build lorebook vector queries. 0 means all messages. */
    readonly LOREBOOK_VECTOR_QUERY_DEPTH_DEFAULT: 10;
    /** Maximum recent-message window for lorebook vector queries. */
    readonly LOREBOOK_VECTOR_QUERY_DEPTH_MAX: 100;
    /** Default minimum cosine similarity for lorebook vector matches. */
    readonly LOREBOOK_VECTOR_SCORE_THRESHOLD_DEFAULT: 0.3;
    /** Default maximum semantic/vector matches a single lorebook may contribute per generation. */
    readonly LOREBOOK_VECTOR_MAX_RESULTS_DEFAULT: 10;
    /** Minimum maximum semantic/vector matches per lorebook. */
    readonly LOREBOOK_VECTOR_MAX_RESULTS_MIN: 1;
    /** Maximum maximum semantic/vector matches per lorebook. */
    readonly LOREBOOK_VECTOR_MAX_RESULTS_MAX: 100;
    /** Echo Chamber: messages per generation */
    readonly ECHO_CHAMBER_MESSAGES: 5;
};
//# sourceMappingURL=defaults.d.ts.map