import type { CharacterStat, CustomTrackerField, GameState, InventoryItem, PresentCharacter, QuestProgress, TrackerFieldLocks, TrackerHiddenFields, WorldCustomField } from "../types/game-state.js";
type WorldTrackerField = "date" | "time" | "location" | "weather" | "temperature";
type TextCharacterField = "emoji" | "name" | "mood" | "appearance" | "outfit" | "thoughts";
type StatField = "name" | "value" | "max";
type InventoryField = "name" | "quantity" | "description" | "location";
type QuestField = "name" | "completed" | "currentStage";
type QuestObjectiveField = "text" | "completed";
type CustomTrackerFieldKey = "name" | "value";
type ObjectiveLockRow = {
    text?: string | null;
};
export declare function normalizeTrackerFieldLocks(value: unknown): TrackerFieldLocks;
export declare function normalizeTrackerHiddenFields(value: unknown): TrackerHiddenFields;
export declare function parseTrackerFieldLocks(value: unknown): TrackerFieldLocks;
export declare function parseTrackerHiddenFields(value: unknown): TrackerHiddenFields;
export declare function trackerFieldLocksAreEmpty(locks: TrackerFieldLocks | null | undefined): boolean;
export declare function trackerHiddenFieldsAreEmpty(hiddenFields: TrackerHiddenFields | null | undefined): boolean;
export declare function trackerFieldLocksAreEqual(left: TrackerFieldLocks | null | undefined, right: TrackerFieldLocks | null | undefined): boolean;
export declare function isTrackerFieldLocked(locks: TrackerFieldLocks | null | undefined, key: string): boolean;
export declare function isTrackerFieldHidden(hiddenFields: TrackerHiddenFields | null | undefined, key: string): boolean;
export declare function toggleTrackerFieldLock(locks: TrackerFieldLocks | null | undefined, key: string): TrackerFieldLocks;
export declare function toggleTrackerFieldHidden(hiddenFields: TrackerHiddenFields | null | undefined, key: string): TrackerHiddenFields;
export declare function removeTrackerArrayItemLocks(locks: TrackerFieldLocks | null | undefined, prefix: string, removedIndex: number): TrackerFieldLocks;
export declare function removeTrackerFieldLockPrefix(locks: TrackerFieldLocks | null | undefined, prefix: string): TrackerFieldLocks;
export declare function renameTrackerFieldLockPrefix(locks: TrackerFieldLocks | null | undefined, fromPrefix: string, toPrefix: string): TrackerFieldLocks;
export declare function worldTrackerLockKey(field: WorldTrackerField): string;
export declare function worldCustomFieldTrackerLockKey(fieldOrIndex: Pick<WorldCustomField, "name"> | number | null | undefined, field: CustomTrackerFieldKey, index?: number): string;
export declare function worldCustomFieldTrackerLockPrefix(fieldOrIndex: Pick<WorldCustomField, "name"> | number | null | undefined, index?: number): string;
export declare function personaStatusTrackerLockKey(): string;
export declare function personaStatTrackerLockKey(statOrIndex: Pick<CharacterStat, "name"> | number | null | undefined, field: StatField, index?: number): string;
export declare function personaStatTrackerLockPrefix(statOrIndex: Pick<CharacterStat, "name"> | number | null | undefined, index?: number): string;
export declare function personaStatsTrackerLockPrefix(): string;
export declare function inventoryTrackerLockKey(itemOrIndex: Pick<InventoryItem, "name"> | number | null | undefined, field: InventoryField, index?: number): string;
export declare function inventoryItemTrackerLockPrefix(itemOrIndex: Pick<InventoryItem, "name"> | number | null | undefined, index?: number): string;
export declare function inventoryTrackerLockPrefix(): string;
export declare function characterTrackerLockPrefix(character: Pick<PresentCharacter, "characterId" | "name"> | null | undefined, index: number): string;
export declare function characterTrackerLockKey(character: Pick<PresentCharacter, "characterId" | "name"> | null | undefined, index: number, field: TextCharacterField): string;
export declare function characterStatTrackerLockKey(character: Pick<PresentCharacter, "characterId" | "name"> | null | undefined, characterIndex: number, statOrIndex: Pick<CharacterStat, "name"> | number | null | undefined, field: StatField, statIndex?: number): string;
export declare function characterStatsTrackerLockPrefix(character: Pick<PresentCharacter, "characterId" | "name"> | null | undefined, index: number): string;
export declare function characterStatTrackerLockPrefix(character: Pick<PresentCharacter, "characterId" | "name"> | null | undefined, characterIndex: number, statOrIndex: Pick<CharacterStat, "name"> | number | null | undefined, statIndex?: number): string;
export declare function removeTrackerCharacterLocks(locks: TrackerFieldLocks | null | undefined, character: Pick<PresentCharacter, "characterId" | "name"> | null | undefined, removedIndex: number): TrackerFieldLocks;
export declare function characterCustomFieldTrackerLockKey(character: Pick<PresentCharacter, "characterId" | "name"> | null | undefined, characterIndex: number, fieldName: string, field: CustomTrackerFieldKey): string;
export declare function questTrackerLockPrefix(quest: Pick<QuestProgress, "questEntryId" | "name"> | null | undefined, index: number): string;
export declare function questTrackerLockKey(quest: Pick<QuestProgress, "questEntryId" | "name"> | null | undefined, index: number, field: QuestField): string;
export declare function questObjectiveTrackerLockKey(quest: Pick<QuestProgress, "questEntryId" | "name"> | null | undefined, questIndex: number, objectiveOrIndex: ObjectiveLockRow | number | null | undefined, field: QuestObjectiveField, objectiveIndex?: number): string;
export declare function questObjectivesTrackerLockPrefix(quest: Pick<QuestProgress, "questEntryId" | "name"> | null | undefined, index: number): string;
export declare function questObjectiveTrackerLockPrefix(quest: Pick<QuestProgress, "questEntryId" | "name"> | null | undefined, questIndex: number, objectiveOrIndex: ObjectiveLockRow | number | null | undefined, objectiveIndex?: number): string;
export declare function removeTrackerQuestLocks(locks: TrackerFieldLocks | null | undefined, quest: Pick<QuestProgress, "questEntryId" | "name"> | null | undefined, removedIndex: number): TrackerFieldLocks;
export declare function customTrackerLockKey(fieldOrIndex: Pick<CustomTrackerField, "name"> | number | null | undefined, field: CustomTrackerFieldKey, index?: number): string;
export declare function customTrackerLockPrefix(): string;
export declare function customTrackerFieldLockPrefix(fieldOrIndex: Pick<CustomTrackerField, "name"> | number | null | undefined, index?: number): string;
export declare function normalizeTrackerFieldLocksForState(locks: TrackerFieldLocks | null | undefined, state: GameState | null | undefined): TrackerFieldLocks;
export declare function applyTrackerFieldLocksToGameStatePatch<T extends Record<string, unknown>>(patch: T, currentState: GameState | null | undefined, fieldLocks?: TrackerFieldLocks | null | undefined): T;
export {};
//# sourceMappingURL=tracker-field-locks.d.ts.map