import type { AgentPromptTemplateOption } from "../types/agent.js";
export declare const GAME_STORYBOARD_ILLUSTRATION_PROMPT_TEMPLATE_ID = "still-keyframes";
export declare const GAME_STORYBOARD_COMIC_PROMPT_TEMPLATE_ID = "comic-page-keyframes";
export declare const GAME_STORYBOARD_STILL_ANIMATION_PROMPT_TEMPLATE_ID = "still-keyframes-animation";
export declare const GAME_STORYBOARD_COMIC_ANIMATION_PROMPT_TEMPLATE_ID = "comic-page-animation";
export declare const GAME_STORYBOARD_ANIMATION_PROMPT_TEMPLATE_ID = "comic-page-animation";
export declare const GAME_STORYBOARD_ANIME_EPISODE_PROMPT_TEMPLATE_ID = "anime-episode-director";
export declare const GAME_STORYBOARD_COLORED_MANGA_PROMPT_TEMPLATE_ID = "colored-manga-keyframes";
export declare const GAME_STORYBOARD_BW_MANGA_PROMPT_TEMPLATE_ID = "bw-manga-keyframes";
export declare const GAME_STORYBOARD_NOVELAI_PROMPT_TEMPLATE_ID = "novelai-keyframes";
export declare const GAME_STORYBOARD_NOVELAI_ANIMATION_PROMPT_TEMPLATE_ID = "novelai-keyframes-animation";
export declare const GAME_STORYBOARD_COLORED_MANGA_ANIMATION_PROMPT_TEMPLATE_ID = "colored-manga-keyframes-animation";
export declare const GAME_STORYBOARD_BW_MANGA_ANIMATION_PROMPT_TEMPLATE_ID = "bw-manga-keyframes-animation";
export declare const GAME_STORYBOARD_KEYFRAME_COUNT_MIN = 1;
export declare const GAME_STORYBOARD_KEYFRAME_COUNT_MAX = 6;
export declare const GAME_STORYBOARD_KEYFRAME_COUNT_DEFAULT = 3;
export declare const GAME_STORYBOARD_ANIMATION_DURATION_SECONDS_MIN = 1;
export declare const GAME_STORYBOARD_ANIMATION_DURATION_SECONDS_MAX = 15;
export declare const GAME_STORYBOARD_ANIMATION_DURATION_SECONDS_DEFAULT = 6;
export declare function normalizeGameStoryboardKeyframeCount(value: unknown, fallback?: number): number;
export declare const GAME_STORYBOARD_PROMPT_TEMPLATE_VARIABLES: readonly ["gameContextBlock", "sourceSectionsBlock", "sourceNarration", "keyframeCount", "durationSeconds", "aspectRatio"];
export declare const GAME_STORYBOARD_KEYFRAME_JSON_SHAPE_LINE = "{ \"title\": string, \"keyframes\": [ { \"title\": string, \"sectionStartIndex\": number, \"sectionEndIndex\": number, \"anchorQuote\": string, \"anchorKind\": \"narration\" | \"dialogue\" | \"readable\" | \"system\", \"narrationBeat\": string, \"imagePrompt\": string, \"characters\": string[] } ] }";
export declare const GAME_STORYBOARD_STILL_PROMPT_TEMPLATE: string;
export declare const GAME_STORYBOARD_NOVELAI_PROMPT_TEMPLATE: string;
export declare const GAME_STORYBOARD_COMIC_PROMPT_TEMPLATE: string;
export declare const GAME_STORYBOARD_COMIC_ANIMATION_PROMPT_TEMPLATE: string;
export declare const GAME_STORYBOARD_ANIME_EPISODE_PROMPT_TEMPLATE: string;
export declare const GAME_STORYBOARD_STILL_ANIMATION_PROMPT_TEMPLATE: string;
export declare const GAME_STORYBOARD_NOVELAI_ANIMATION_PROMPT_TEMPLATE: string;
export declare const GAME_STORYBOARD_COLORED_MANGA_ANIMATION_PROMPT_TEMPLATE: string;
export declare const GAME_STORYBOARD_BW_MANGA_ANIMATION_PROMPT_TEMPLATE: string;
export declare const GAME_STORYBOARD_COLORED_MANGA_PROMPT_TEMPLATE: string;
export declare const GAME_STORYBOARD_BW_MANGA_PROMPT_TEMPLATE: string;
export declare const GAME_STORYBOARD_ILLUSTRATION_PROMPT_TEMPLATES: AgentPromptTemplateOption[];
export declare const GAME_STORYBOARD_ANIMATION_PROMPT_TEMPLATES: AgentPromptTemplateOption[];
export declare const GAME_STORYBOARD_BUILT_IN_PROMPT_TEMPLATES: AgentPromptTemplateOption[];
export type GameStoryboardPromptTemplateKind = "illustration" | "animation";
export declare function getGameStoryboardPromptTemplateKind(template: AgentPromptTemplateOption, selectedAnimationTemplateId?: string | null): GameStoryboardPromptTemplateKind;
//# sourceMappingURL=game-storyboard-prompts.d.ts.map