import { z } from "zod";
export declare const apiProviderSchema: z.ZodEnum<["openai", "openai_chatgpt", "anthropic", "claude_subscription", "grok_subscription", "google", "google_vertex", "mistral", "cohere", "openrouter", "nanogpt", "xai", "custom", "image_generation", "video_generation"]>;
export declare const createConnectionSchema: z.ZodObject<{
    name: z.ZodString;
    provider: z.ZodEnum<["openai", "openai_chatgpt", "anthropic", "claude_subscription", "grok_subscription", "google", "google_vertex", "mistral", "cohere", "openrouter", "nanogpt", "xai", "custom", "image_generation", "video_generation"]>;
    baseUrl: z.ZodDefault<z.ZodUnion<[z.ZodString, z.ZodLiteral<"">]>>;
    apiKey: z.ZodDefault<z.ZodString>;
    model: z.ZodDefault<z.ZodString>;
    imagePath: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    maxContext: z.ZodDefault<z.ZodNumber>;
    isDefault: z.ZodDefault<z.ZodBoolean>;
    fallbackForMain: z.ZodDefault<z.ZodBoolean>;
    useForRandom: z.ZodDefault<z.ZodBoolean>;
    defaultForAgents: z.ZodDefault<z.ZodBoolean>;
    fallbackForAgents: z.ZodDefault<z.ZodBoolean>;
    enableCaching: z.ZodDefault<z.ZodBoolean>;
    anthropicExtendedCacheTtl: z.ZodDefault<z.ZodBoolean>;
    cachingAtDepth: z.ZodDefault<z.ZodNumber>;
    embeddingModel: z.ZodDefault<z.ZodString>;
    embeddingBaseUrl: z.ZodDefault<z.ZodUnion<[z.ZodString, z.ZodLiteral<"">]>>;
    embeddingConnectionId: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    openrouterProvider: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    imageGenerationSource: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    comfyuiWorkflow: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    imageService: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    imageEndpointId: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    videoGenerationSource: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    videoService: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    promptPresetId: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    maxTokensOverride: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    maxParallelJobs: z.ZodDefault<z.ZodNumber>;
    treatAsLocalEndpoint: z.ZodDefault<z.ZodBoolean>;
    claudeFastMode: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    baseUrl: string;
    apiKey: string;
    model: string;
    name: string;
    promptPresetId: string | null;
    imagePath: string | null;
    maxContext: number;
    isDefault: boolean;
    provider: "openai" | "xai" | "custom" | "openai_chatgpt" | "anthropic" | "claude_subscription" | "grok_subscription" | "google" | "google_vertex" | "mistral" | "cohere" | "openrouter" | "nanogpt" | "image_generation" | "video_generation";
    fallbackForMain: boolean;
    useForRandom: boolean;
    defaultForAgents: boolean;
    fallbackForAgents: boolean;
    enableCaching: boolean;
    anthropicExtendedCacheTtl: boolean;
    cachingAtDepth: number;
    embeddingModel: string;
    embeddingBaseUrl: string;
    embeddingConnectionId: string | null;
    openrouterProvider: string | null;
    imageGenerationSource: string | null;
    comfyuiWorkflow: string | null;
    imageService: string | null;
    imageEndpointId: string | null;
    videoGenerationSource: string | null;
    videoService: string | null;
    maxTokensOverride: number | null;
    maxParallelJobs: number;
    treatAsLocalEndpoint: boolean;
    claudeFastMode: boolean;
}, {
    name: string;
    provider: "openai" | "xai" | "custom" | "openai_chatgpt" | "anthropic" | "claude_subscription" | "grok_subscription" | "google" | "google_vertex" | "mistral" | "cohere" | "openrouter" | "nanogpt" | "image_generation" | "video_generation";
    baseUrl?: string | undefined;
    apiKey?: string | undefined;
    model?: string | undefined;
    promptPresetId?: string | null | undefined;
    imagePath?: string | null | undefined;
    maxContext?: number | undefined;
    isDefault?: boolean | undefined;
    fallbackForMain?: boolean | undefined;
    useForRandom?: boolean | undefined;
    defaultForAgents?: boolean | undefined;
    fallbackForAgents?: boolean | undefined;
    enableCaching?: boolean | undefined;
    anthropicExtendedCacheTtl?: boolean | undefined;
    cachingAtDepth?: number | undefined;
    embeddingModel?: string | undefined;
    embeddingBaseUrl?: string | undefined;
    embeddingConnectionId?: string | null | undefined;
    openrouterProvider?: string | null | undefined;
    imageGenerationSource?: string | null | undefined;
    comfyuiWorkflow?: string | null | undefined;
    imageService?: string | null | undefined;
    imageEndpointId?: string | null | undefined;
    videoGenerationSource?: string | null | undefined;
    videoService?: string | null | undefined;
    maxTokensOverride?: number | null | undefined;
    maxParallelJobs?: number | undefined;
    treatAsLocalEndpoint?: boolean | undefined;
    claudeFastMode?: boolean | undefined;
}>;
export type CreateConnectionInput = z.infer<typeof createConnectionSchema>;
//# sourceMappingURL=connection.schema.d.ts.map