import { z } from "zod";
import type { GameNpc, HudWidget } from "../types/game.js";
export declare const SCENE_ANALYSIS_NARRATION_MAX_CHARS = 50000;
export declare const SIDECAR_SCENE_ANALYSIS_NARRATION_BUDGET_CHARS = 16000;
export declare const sceneSpotifyTrackCandidateSchema: z.ZodObject<{
    uri: z.ZodString;
    name: z.ZodString;
    artist: z.ZodString;
    album: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    position: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    score: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
}, "strip", z.ZodTypeAny, {
    name: string;
    artist: string;
    uri: string;
    position?: number | null | undefined;
    album?: string | null | undefined;
    score?: number | null | undefined;
}, {
    name: string;
    artist: string;
    uri: string;
    position?: number | null | undefined;
    album?: string | null | undefined;
    score?: number | null | undefined;
}>;
export declare const sceneAnalysisContextSchema: z.ZodObject<{
    currentState: z.ZodEnum<["exploration", "dialogue", "combat", "travel_rest"]>;
    turnNumber: z.ZodOptional<z.ZodNumber>;
    availableBackgrounds: z.ZodArray<z.ZodString, "many">;
    availableSfx: z.ZodArray<z.ZodString, "many">;
    activeWidgets: z.ZodArray<z.ZodType<HudWidget, z.ZodTypeDef, HudWidget>, "many">;
    trackedNpcs: z.ZodArray<z.ZodType<GameNpc, z.ZodTypeDef, GameNpc>, "many">;
    characterNames: z.ZodArray<z.ZodString, "many">;
    currentBackground: z.ZodNullable<z.ZodString>;
    currentMusic: z.ZodNullable<z.ZodString>;
    recentMusic: z.ZodDefault<z.ZodOptional<z.ZodArray<z.ZodString, "many">>>;
    useSpotifyMusic: z.ZodDefault<z.ZodOptional<z.ZodBoolean>>;
    availableSpotifyTracks: z.ZodDefault<z.ZodOptional<z.ZodArray<z.ZodObject<{
        uri: z.ZodString;
        name: z.ZodString;
        artist: z.ZodString;
        album: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        position: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
        score: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    }, "strip", z.ZodTypeAny, {
        name: string;
        artist: string;
        uri: string;
        position?: number | null | undefined;
        album?: string | null | undefined;
        score?: number | null | undefined;
    }, {
        name: string;
        artist: string;
        uri: string;
        position?: number | null | undefined;
        album?: string | null | undefined;
        score?: number | null | undefined;
    }>, "many">>>;
    currentSpotifyTrack: z.ZodDefault<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    recentSpotifyTracks: z.ZodDefault<z.ZodOptional<z.ZodArray<z.ZodString, "many">>>;
    currentAmbient: z.ZodDefault<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    currentLocation: z.ZodDefault<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    currentWeather: z.ZodNullable<z.ZodString>;
    currentTimeOfDay: z.ZodNullable<z.ZodString>;
    genre: z.ZodDefault<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    setting: z.ZodDefault<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    worldOverview: z.ZodDefault<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    canGenerateBackgrounds: z.ZodOptional<z.ZodBoolean>;
    canGenerateIllustrations: z.ZodOptional<z.ZodBoolean>;
    artStylePrompt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    imagePromptInstructions: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    currentBackground: string | null;
    currentState: "combat" | "exploration" | "dialogue" | "travel_rest";
    availableBackgrounds: string[];
    availableSfx: string[];
    activeWidgets: HudWidget[];
    trackedNpcs: GameNpc[];
    characterNames: string[];
    currentMusic: string | null;
    recentMusic: string[];
    useSpotifyMusic: boolean;
    availableSpotifyTracks: {
        name: string;
        artist: string;
        uri: string;
        position?: number | null | undefined;
        album?: string | null | undefined;
        score?: number | null | undefined;
    }[];
    currentSpotifyTrack: string | null;
    recentSpotifyTracks: string[];
    currentAmbient: string | null;
    currentLocation: string | null;
    currentWeather: string | null;
    currentTimeOfDay: string | null;
    genre: string | null;
    setting: string | null;
    worldOverview: string | null;
    turnNumber?: number | undefined;
    canGenerateBackgrounds?: boolean | undefined;
    canGenerateIllustrations?: boolean | undefined;
    artStylePrompt?: string | null | undefined;
    imagePromptInstructions?: string | null | undefined;
}, {
    currentBackground: string | null;
    currentState: "combat" | "exploration" | "dialogue" | "travel_rest";
    availableBackgrounds: string[];
    availableSfx: string[];
    activeWidgets: HudWidget[];
    trackedNpcs: GameNpc[];
    characterNames: string[];
    currentMusic: string | null;
    currentWeather: string | null;
    currentTimeOfDay: string | null;
    turnNumber?: number | undefined;
    recentMusic?: string[] | undefined;
    useSpotifyMusic?: boolean | undefined;
    availableSpotifyTracks?: {
        name: string;
        artist: string;
        uri: string;
        position?: number | null | undefined;
        album?: string | null | undefined;
        score?: number | null | undefined;
    }[] | undefined;
    currentSpotifyTrack?: string | null | undefined;
    recentSpotifyTracks?: string[] | undefined;
    currentAmbient?: string | null | undefined;
    currentLocation?: string | null | undefined;
    genre?: string | null | undefined;
    setting?: string | null | undefined;
    worldOverview?: string | null | undefined;
    canGenerateBackgrounds?: boolean | undefined;
    canGenerateIllustrations?: boolean | undefined;
    artStylePrompt?: string | null | undefined;
    imagePromptInstructions?: string | null | undefined;
}>;
export declare const sceneAnalysisRequestSchema: z.ZodObject<{
    narration: z.ZodString;
    playerAction: z.ZodOptional<z.ZodString>;
    context: z.ZodObject<{
        currentState: z.ZodEnum<["exploration", "dialogue", "combat", "travel_rest"]>;
        turnNumber: z.ZodOptional<z.ZodNumber>;
        availableBackgrounds: z.ZodArray<z.ZodString, "many">;
        availableSfx: z.ZodArray<z.ZodString, "many">;
        activeWidgets: z.ZodArray<z.ZodType<HudWidget, z.ZodTypeDef, HudWidget>, "many">;
        trackedNpcs: z.ZodArray<z.ZodType<GameNpc, z.ZodTypeDef, GameNpc>, "many">;
        characterNames: z.ZodArray<z.ZodString, "many">;
        currentBackground: z.ZodNullable<z.ZodString>;
        currentMusic: z.ZodNullable<z.ZodString>;
        recentMusic: z.ZodDefault<z.ZodOptional<z.ZodArray<z.ZodString, "many">>>;
        useSpotifyMusic: z.ZodDefault<z.ZodOptional<z.ZodBoolean>>;
        availableSpotifyTracks: z.ZodDefault<z.ZodOptional<z.ZodArray<z.ZodObject<{
            uri: z.ZodString;
            name: z.ZodString;
            artist: z.ZodString;
            album: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            position: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
            score: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
        }, "strip", z.ZodTypeAny, {
            name: string;
            artist: string;
            uri: string;
            position?: number | null | undefined;
            album?: string | null | undefined;
            score?: number | null | undefined;
        }, {
            name: string;
            artist: string;
            uri: string;
            position?: number | null | undefined;
            album?: string | null | undefined;
            score?: number | null | undefined;
        }>, "many">>>;
        currentSpotifyTrack: z.ZodDefault<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
        recentSpotifyTracks: z.ZodDefault<z.ZodOptional<z.ZodArray<z.ZodString, "many">>>;
        currentAmbient: z.ZodDefault<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
        currentLocation: z.ZodDefault<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
        currentWeather: z.ZodNullable<z.ZodString>;
        currentTimeOfDay: z.ZodNullable<z.ZodString>;
        genre: z.ZodDefault<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
        setting: z.ZodDefault<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
        worldOverview: z.ZodDefault<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
        canGenerateBackgrounds: z.ZodOptional<z.ZodBoolean>;
        canGenerateIllustrations: z.ZodOptional<z.ZodBoolean>;
        artStylePrompt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        imagePromptInstructions: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    }, "strip", z.ZodTypeAny, {
        currentBackground: string | null;
        currentState: "combat" | "exploration" | "dialogue" | "travel_rest";
        availableBackgrounds: string[];
        availableSfx: string[];
        activeWidgets: HudWidget[];
        trackedNpcs: GameNpc[];
        characterNames: string[];
        currentMusic: string | null;
        recentMusic: string[];
        useSpotifyMusic: boolean;
        availableSpotifyTracks: {
            name: string;
            artist: string;
            uri: string;
            position?: number | null | undefined;
            album?: string | null | undefined;
            score?: number | null | undefined;
        }[];
        currentSpotifyTrack: string | null;
        recentSpotifyTracks: string[];
        currentAmbient: string | null;
        currentLocation: string | null;
        currentWeather: string | null;
        currentTimeOfDay: string | null;
        genre: string | null;
        setting: string | null;
        worldOverview: string | null;
        turnNumber?: number | undefined;
        canGenerateBackgrounds?: boolean | undefined;
        canGenerateIllustrations?: boolean | undefined;
        artStylePrompt?: string | null | undefined;
        imagePromptInstructions?: string | null | undefined;
    }, {
        currentBackground: string | null;
        currentState: "combat" | "exploration" | "dialogue" | "travel_rest";
        availableBackgrounds: string[];
        availableSfx: string[];
        activeWidgets: HudWidget[];
        trackedNpcs: GameNpc[];
        characterNames: string[];
        currentMusic: string | null;
        currentWeather: string | null;
        currentTimeOfDay: string | null;
        turnNumber?: number | undefined;
        recentMusic?: string[] | undefined;
        useSpotifyMusic?: boolean | undefined;
        availableSpotifyTracks?: {
            name: string;
            artist: string;
            uri: string;
            position?: number | null | undefined;
            album?: string | null | undefined;
            score?: number | null | undefined;
        }[] | undefined;
        currentSpotifyTrack?: string | null | undefined;
        recentSpotifyTracks?: string[] | undefined;
        currentAmbient?: string | null | undefined;
        currentLocation?: string | null | undefined;
        genre?: string | null | undefined;
        setting?: string | null | undefined;
        worldOverview?: string | null | undefined;
        canGenerateBackgrounds?: boolean | undefined;
        canGenerateIllustrations?: boolean | undefined;
        artStylePrompt?: string | null | undefined;
        imagePromptInstructions?: string | null | undefined;
    }>;
    debugMode: z.ZodDefault<z.ZodOptional<z.ZodBoolean>>;
}, "strip", z.ZodTypeAny, {
    debugMode: boolean;
    narration: string;
    context: {
        currentBackground: string | null;
        currentState: "combat" | "exploration" | "dialogue" | "travel_rest";
        availableBackgrounds: string[];
        availableSfx: string[];
        activeWidgets: HudWidget[];
        trackedNpcs: GameNpc[];
        characterNames: string[];
        currentMusic: string | null;
        recentMusic: string[];
        useSpotifyMusic: boolean;
        availableSpotifyTracks: {
            name: string;
            artist: string;
            uri: string;
            position?: number | null | undefined;
            album?: string | null | undefined;
            score?: number | null | undefined;
        }[];
        currentSpotifyTrack: string | null;
        recentSpotifyTracks: string[];
        currentAmbient: string | null;
        currentLocation: string | null;
        currentWeather: string | null;
        currentTimeOfDay: string | null;
        genre: string | null;
        setting: string | null;
        worldOverview: string | null;
        turnNumber?: number | undefined;
        canGenerateBackgrounds?: boolean | undefined;
        canGenerateIllustrations?: boolean | undefined;
        artStylePrompt?: string | null | undefined;
        imagePromptInstructions?: string | null | undefined;
    };
    playerAction?: string | undefined;
}, {
    narration: string;
    context: {
        currentBackground: string | null;
        currentState: "combat" | "exploration" | "dialogue" | "travel_rest";
        availableBackgrounds: string[];
        availableSfx: string[];
        activeWidgets: HudWidget[];
        trackedNpcs: GameNpc[];
        characterNames: string[];
        currentMusic: string | null;
        currentWeather: string | null;
        currentTimeOfDay: string | null;
        turnNumber?: number | undefined;
        recentMusic?: string[] | undefined;
        useSpotifyMusic?: boolean | undefined;
        availableSpotifyTracks?: {
            name: string;
            artist: string;
            uri: string;
            position?: number | null | undefined;
            album?: string | null | undefined;
            score?: number | null | undefined;
        }[] | undefined;
        currentSpotifyTrack?: string | null | undefined;
        recentSpotifyTracks?: string[] | undefined;
        currentAmbient?: string | null | undefined;
        currentLocation?: string | null | undefined;
        genre?: string | null | undefined;
        setting?: string | null | undefined;
        worldOverview?: string | null | undefined;
        canGenerateBackgrounds?: boolean | undefined;
        canGenerateIllustrations?: boolean | undefined;
        artStylePrompt?: string | null | undefined;
        imagePromptInstructions?: string | null | undefined;
    };
    debugMode?: boolean | undefined;
    playerAction?: string | undefined;
}>;
export type SceneAnalysisContextRequest = z.input<typeof sceneAnalysisContextSchema>;
export type SceneAnalysisRequest = z.input<typeof sceneAnalysisRequestSchema>;
//# sourceMappingURL=scene-analysis.schema.d.ts.map