import { z } from "zod";
export declare const LOREBOOK_CATEGORY_VALUES: readonly ["world", "character", "npc", "spellbook", "uncategorized"];
export type LorebookCategoryValue = (typeof LOREBOOK_CATEGORY_VALUES)[number];
export declare const lorebookCategorySchema: z.ZodEnum<["world", "character", "npc", "spellbook", "uncategorized"]>;
export declare function normalizeLorebookCategory(value: unknown): LorebookCategoryValue;
export declare const lorebookScopeModeSchema: z.ZodEnum<["all", "disabled", "specific"]>;
export declare const lorebookScopeSchema: z.ZodObject<{
    mode: z.ZodDefault<z.ZodEnum<["all", "disabled", "specific"]>>;
    chatIds: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
}, "strip", z.ZodTypeAny, {
    mode: "all" | "disabled" | "specific";
    chatIds: string[];
}, {
    mode?: "all" | "disabled" | "specific" | undefined;
    chatIds?: string[] | undefined;
}>;
export declare const selectiveLogicSchema: z.ZodEnum<["and", "and_all", "or", "not", "not_all"]>;
export declare const lorebookFilterModeSchema: z.ZodEnum<["any", "include", "exclude"]>;
export declare const lorebookMatchingSourceSchema: z.ZodEnum<["character_name", "character_description", "character_personality", "character_scenario", "character_tags", "persona_description", "persona_tags"]>;
export declare const activationConditionSchema: z.ZodObject<{
    field: z.ZodString;
    operator: z.ZodEnum<["equals", "not_equals", "contains", "not_contains", "gt", "lt"]>;
    value: z.ZodString;
}, "strip", z.ZodTypeAny, {
    value: string;
    field: string;
    operator: "lt" | "equals" | "not_equals" | "contains" | "not_contains" | "gt";
}, {
    value: string;
    field: string;
    operator: "lt" | "equals" | "not_equals" | "contains" | "not_contains" | "gt";
}>;
export declare const lorebookScheduleSchema: z.ZodObject<{
    activeTimes: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    activeDates: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    activeLocations: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
}, "strip", z.ZodTypeAny, {
    activeTimes: string[];
    activeDates: string[];
    activeLocations: string[];
}, {
    activeTimes?: string[] | undefined;
    activeDates?: string[] | undefined;
    activeLocations?: string[] | undefined;
}>;
export declare const createLorebookFolderSchema: z.ZodObject<{
    name: z.ZodString;
    enabled: z.ZodDefault<z.ZodBoolean>;
    parentFolderId: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    order: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    enabled: boolean;
    name: string;
    parentFolderId: string | null;
    order: number;
}, {
    name: string;
    enabled?: boolean | undefined;
    parentFolderId?: string | null | undefined;
    order?: number | undefined;
}>;
export declare const updateLorebookFolderSchema: z.ZodObject<{
    name: z.ZodOptional<z.ZodString>;
    enabled: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    parentFolderId: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodString>>>;
    order: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
}, "strip", z.ZodTypeAny, {
    enabled?: boolean | undefined;
    name?: string | undefined;
    parentFolderId?: string | null | undefined;
    order?: number | undefined;
}, {
    enabled?: boolean | undefined;
    name?: string | undefined;
    parentFolderId?: string | null | undefined;
    order?: number | undefined;
}>;
export declare const createLorebookSchema: z.ZodEffects<z.ZodObject<{
    name: z.ZodString;
    description: z.ZodDefault<z.ZodString>;
    category: z.ZodDefault<z.ZodEnum<["world", "character", "npc", "spellbook", "uncategorized"]>>;
    imagePath: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    scanDepth: z.ZodDefault<z.ZodNumber>;
    tokenBudget: z.ZodDefault<z.ZodNumber>;
    entryLimit: z.ZodDefault<z.ZodNumber>;
    recursiveScanning: z.ZodDefault<z.ZodBoolean>;
    maxRecursionDepth: z.ZodDefault<z.ZodNumber>;
    excludeFromVectorization: z.ZodDefault<z.ZodBoolean>;
    vectorQueryDepth: z.ZodDefault<z.ZodNumber>;
    vectorScoreThreshold: z.ZodDefault<z.ZodNumber>;
    vectorMaxResults: z.ZodDefault<z.ZodNumber>;
    characterId: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    characterIds: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    personaId: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    personaIds: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    chatId: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    isGlobal: z.ZodDefault<z.ZodBoolean>;
    enabled: z.ZodDefault<z.ZodBoolean>;
    scope: z.ZodDefault<z.ZodObject<{
        mode: z.ZodDefault<z.ZodEnum<["all", "disabled", "specific"]>>;
        chatIds: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    }, "strip", z.ZodTypeAny, {
        mode: "all" | "disabled" | "specific";
        chatIds: string[];
    }, {
        mode?: "all" | "disabled" | "specific" | undefined;
        chatIds?: string[] | undefined;
    }>>;
    tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    generatedBy: z.ZodDefault<z.ZodEffects<z.ZodNullable<z.ZodEnum<["user", "agent", "import", "lorebook-maker"]>>, "user" | "agent" | "import" | null, "user" | "agent" | "import" | "lorebook-maker" | null>>;
    sourceAgentId: z.ZodDefault<z.ZodNullable<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    characterId: string | null;
    enabled: boolean;
    name: string;
    description: string;
    category: "world" | "character" | "npc" | "spellbook" | "uncategorized";
    scope: {
        mode: "all" | "disabled" | "specific";
        chatIds: string[];
    };
    chatId: string | null;
    characterIds: string[];
    personaId: string | null;
    tags: string[];
    personaIds: string[];
    imagePath: string | null;
    scanDepth: number;
    tokenBudget: number;
    entryLimit: number;
    recursiveScanning: boolean;
    maxRecursionDepth: number;
    excludeFromVectorization: boolean;
    vectorQueryDepth: number;
    vectorScoreThreshold: number;
    vectorMaxResults: number;
    isGlobal: boolean;
    generatedBy: "user" | "agent" | "import" | null;
    sourceAgentId: string | null;
}, {
    name: string;
    characterId?: string | null | undefined;
    enabled?: boolean | undefined;
    description?: string | undefined;
    category?: "world" | "character" | "npc" | "spellbook" | "uncategorized" | undefined;
    scope?: {
        mode?: "all" | "disabled" | "specific" | undefined;
        chatIds?: string[] | undefined;
    } | undefined;
    chatId?: string | null | undefined;
    characterIds?: string[] | undefined;
    personaId?: string | null | undefined;
    tags?: string[] | undefined;
    personaIds?: string[] | undefined;
    imagePath?: string | null | undefined;
    scanDepth?: number | undefined;
    tokenBudget?: number | undefined;
    entryLimit?: number | undefined;
    recursiveScanning?: boolean | undefined;
    maxRecursionDepth?: number | undefined;
    excludeFromVectorization?: boolean | undefined;
    vectorQueryDepth?: number | undefined;
    vectorScoreThreshold?: number | undefined;
    vectorMaxResults?: number | undefined;
    isGlobal?: boolean | undefined;
    generatedBy?: "user" | "agent" | "import" | "lorebook-maker" | null | undefined;
    sourceAgentId?: string | null | undefined;
}>, {
    characterId: string | null;
    enabled: boolean;
    name: string;
    description: string;
    category: "world" | "character" | "npc" | "spellbook" | "uncategorized";
    scope: {
        mode: "all" | "disabled" | "specific";
        chatIds: string[];
    };
    chatId: string | null;
    characterIds: string[];
    personaId: string | null;
    tags: string[];
    personaIds: string[];
    imagePath: string | null;
    scanDepth: number;
    tokenBudget: number;
    entryLimit: number;
    recursiveScanning: boolean;
    maxRecursionDepth: number;
    excludeFromVectorization: boolean;
    vectorQueryDepth: number;
    vectorScoreThreshold: number;
    vectorMaxResults: number;
    isGlobal: boolean;
    generatedBy: "user" | "agent" | "import" | null;
    sourceAgentId: string | null;
}, {
    name: string;
    characterId?: string | null | undefined;
    enabled?: boolean | undefined;
    description?: string | undefined;
    category?: "world" | "character" | "npc" | "spellbook" | "uncategorized" | undefined;
    scope?: {
        mode?: "all" | "disabled" | "specific" | undefined;
        chatIds?: string[] | undefined;
    } | undefined;
    chatId?: string | null | undefined;
    characterIds?: string[] | undefined;
    personaId?: string | null | undefined;
    tags?: string[] | undefined;
    personaIds?: string[] | undefined;
    imagePath?: string | null | undefined;
    scanDepth?: number | undefined;
    tokenBudget?: number | undefined;
    entryLimit?: number | undefined;
    recursiveScanning?: boolean | undefined;
    maxRecursionDepth?: number | undefined;
    excludeFromVectorization?: boolean | undefined;
    vectorQueryDepth?: number | undefined;
    vectorScoreThreshold?: number | undefined;
    vectorMaxResults?: number | undefined;
    isGlobal?: boolean | undefined;
    generatedBy?: "user" | "agent" | "import" | "lorebook-maker" | null | undefined;
    sourceAgentId?: string | null | undefined;
}>;
export declare const updateLorebookSchema: z.ZodEffects<z.ZodObject<{
    name: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodDefault<z.ZodString>>;
    category: z.ZodOptional<z.ZodDefault<z.ZodEnum<["world", "character", "npc", "spellbook", "uncategorized"]>>>;
    imagePath: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodString>>>;
    scanDepth: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    tokenBudget: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    entryLimit: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    recursiveScanning: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    maxRecursionDepth: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    excludeFromVectorization: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    vectorQueryDepth: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    vectorScoreThreshold: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    vectorMaxResults: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    characterId: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodString>>>;
    characterIds: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString, "many">>>;
    personaId: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodString>>>;
    personaIds: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString, "many">>>;
    chatId: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodString>>>;
    isGlobal: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    enabled: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    scope: z.ZodOptional<z.ZodDefault<z.ZodObject<{
        mode: z.ZodDefault<z.ZodEnum<["all", "disabled", "specific"]>>;
        chatIds: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    }, "strip", z.ZodTypeAny, {
        mode: "all" | "disabled" | "specific";
        chatIds: string[];
    }, {
        mode?: "all" | "disabled" | "specific" | undefined;
        chatIds?: string[] | undefined;
    }>>>;
    tags: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString, "many">>>;
    generatedBy: z.ZodOptional<z.ZodDefault<z.ZodEffects<z.ZodNullable<z.ZodEnum<["user", "agent", "import", "lorebook-maker"]>>, "user" | "agent" | "import" | null, "user" | "agent" | "import" | "lorebook-maker" | null>>>;
    sourceAgentId: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodString>>>;
}, "strip", z.ZodTypeAny, {
    characterId?: string | null | undefined;
    enabled?: boolean | undefined;
    name?: string | undefined;
    description?: string | undefined;
    category?: "world" | "character" | "npc" | "spellbook" | "uncategorized" | undefined;
    scope?: {
        mode: "all" | "disabled" | "specific";
        chatIds: string[];
    } | undefined;
    chatId?: string | null | undefined;
    characterIds?: string[] | undefined;
    personaId?: string | null | undefined;
    tags?: string[] | undefined;
    personaIds?: string[] | undefined;
    imagePath?: string | null | undefined;
    scanDepth?: number | undefined;
    tokenBudget?: number | undefined;
    entryLimit?: number | undefined;
    recursiveScanning?: boolean | undefined;
    maxRecursionDepth?: number | undefined;
    excludeFromVectorization?: boolean | undefined;
    vectorQueryDepth?: number | undefined;
    vectorScoreThreshold?: number | undefined;
    vectorMaxResults?: number | undefined;
    isGlobal?: boolean | undefined;
    generatedBy?: "user" | "agent" | "import" | null | undefined;
    sourceAgentId?: string | null | undefined;
}, {
    characterId?: string | null | undefined;
    enabled?: boolean | undefined;
    name?: string | undefined;
    description?: string | undefined;
    category?: "world" | "character" | "npc" | "spellbook" | "uncategorized" | undefined;
    scope?: {
        mode?: "all" | "disabled" | "specific" | undefined;
        chatIds?: string[] | undefined;
    } | undefined;
    chatId?: string | null | undefined;
    characterIds?: string[] | undefined;
    personaId?: string | null | undefined;
    tags?: string[] | undefined;
    personaIds?: string[] | undefined;
    imagePath?: string | null | undefined;
    scanDepth?: number | undefined;
    tokenBudget?: number | undefined;
    entryLimit?: number | undefined;
    recursiveScanning?: boolean | undefined;
    maxRecursionDepth?: number | undefined;
    excludeFromVectorization?: boolean | undefined;
    vectorQueryDepth?: number | undefined;
    vectorScoreThreshold?: number | undefined;
    vectorMaxResults?: number | undefined;
    isGlobal?: boolean | undefined;
    generatedBy?: "user" | "agent" | "import" | "lorebook-maker" | null | undefined;
    sourceAgentId?: string | null | undefined;
}>, {
    characterId?: string | null | undefined;
    enabled?: boolean | undefined;
    name?: string | undefined;
    description?: string | undefined;
    category?: "world" | "character" | "npc" | "spellbook" | "uncategorized" | undefined;
    scope?: {
        mode: "all" | "disabled" | "specific";
        chatIds: string[];
    } | undefined;
    chatId?: string | null | undefined;
    characterIds?: string[] | undefined;
    personaId?: string | null | undefined;
    tags?: string[] | undefined;
    personaIds?: string[] | undefined;
    imagePath?: string | null | undefined;
    scanDepth?: number | undefined;
    tokenBudget?: number | undefined;
    entryLimit?: number | undefined;
    recursiveScanning?: boolean | undefined;
    maxRecursionDepth?: number | undefined;
    excludeFromVectorization?: boolean | undefined;
    vectorQueryDepth?: number | undefined;
    vectorScoreThreshold?: number | undefined;
    vectorMaxResults?: number | undefined;
    isGlobal?: boolean | undefined;
    generatedBy?: "user" | "agent" | "import" | null | undefined;
    sourceAgentId?: string | null | undefined;
}, {
    characterId?: string | null | undefined;
    enabled?: boolean | undefined;
    name?: string | undefined;
    description?: string | undefined;
    category?: "world" | "character" | "npc" | "spellbook" | "uncategorized" | undefined;
    scope?: {
        mode?: "all" | "disabled" | "specific" | undefined;
        chatIds?: string[] | undefined;
    } | undefined;
    chatId?: string | null | undefined;
    characterIds?: string[] | undefined;
    personaId?: string | null | undefined;
    tags?: string[] | undefined;
    personaIds?: string[] | undefined;
    imagePath?: string | null | undefined;
    scanDepth?: number | undefined;
    tokenBudget?: number | undefined;
    entryLimit?: number | undefined;
    recursiveScanning?: boolean | undefined;
    maxRecursionDepth?: number | undefined;
    excludeFromVectorization?: boolean | undefined;
    vectorQueryDepth?: number | undefined;
    vectorScoreThreshold?: number | undefined;
    vectorMaxResults?: number | undefined;
    isGlobal?: boolean | undefined;
    generatedBy?: "user" | "agent" | "import" | "lorebook-maker" | null | undefined;
    sourceAgentId?: string | null | undefined;
}>;
export declare const createLorebookEntrySchema: z.ZodObject<{
    lorebookId: z.ZodString;
    name: z.ZodString;
    content: z.ZodDefault<z.ZodString>;
    description: z.ZodDefault<z.ZodString>;
    keys: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    secondaryKeys: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    enabled: z.ZodDefault<z.ZodBoolean>;
    constant: z.ZodDefault<z.ZodBoolean>;
    selective: z.ZodDefault<z.ZodBoolean>;
    selectiveLogic: z.ZodDefault<z.ZodEnum<["and", "and_all", "or", "not", "not_all"]>>;
    probability: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    scanDepth: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    matchWholeWords: z.ZodDefault<z.ZodBoolean>;
    caseSensitive: z.ZodDefault<z.ZodBoolean>;
    useRegex: z.ZodDefault<z.ZodBoolean>;
    characterFilterMode: z.ZodDefault<z.ZodEnum<["any", "include", "exclude"]>>;
    characterFilterIds: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    characterTagFilterMode: z.ZodDefault<z.ZodEnum<["any", "include", "exclude"]>>;
    characterTagFilters: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    generationTriggerFilterMode: z.ZodDefault<z.ZodEnum<["any", "include", "exclude"]>>;
    generationTriggerFilters: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    additionalMatchingSources: z.ZodDefault<z.ZodArray<z.ZodEnum<["character_name", "character_description", "character_personality", "character_scenario", "character_tags", "persona_description", "persona_tags"]>, "many">>;
    position: z.ZodDefault<z.ZodNumber>;
    depth: z.ZodDefault<z.ZodNumber>;
    order: z.ZodDefault<z.ZodNumber>;
    role: z.ZodDefault<z.ZodEnum<["system", "user", "assistant"]>>;
    sticky: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    cooldown: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    delay: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    ephemeral: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    group: z.ZodDefault<z.ZodString>;
    groupWeight: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    /** Optional folder this entry belongs to. Null/omitted = root level. */
    folderId: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    preventRecursion: z.ZodDefault<z.ZodBoolean>;
    excludeRecursion: z.ZodDefault<z.ZodBoolean>;
    delayUntilRecursion: z.ZodDefault<z.ZodBoolean>;
    locked: z.ZodDefault<z.ZodBoolean>;
    tag: z.ZodDefault<z.ZodString>;
    relationships: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodString>>;
    dynamicState: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    activationConditions: z.ZodDefault<z.ZodArray<z.ZodObject<{
        field: z.ZodString;
        operator: z.ZodEnum<["equals", "not_equals", "contains", "not_contains", "gt", "lt"]>;
        value: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        value: string;
        field: string;
        operator: "lt" | "equals" | "not_equals" | "contains" | "not_contains" | "gt";
    }, {
        value: string;
        field: string;
        operator: "lt" | "equals" | "not_equals" | "contains" | "not_contains" | "gt";
    }>, "many">>;
    schedule: z.ZodDefault<z.ZodNullable<z.ZodObject<{
        activeTimes: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        activeDates: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        activeLocations: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    }, "strip", z.ZodTypeAny, {
        activeTimes: string[];
        activeDates: string[];
        activeLocations: string[];
    }, {
        activeTimes?: string[] | undefined;
        activeDates?: string[] | undefined;
        activeLocations?: string[] | undefined;
    }>>>;
    excludeFromVectorization: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    keys: string[];
    enabled: boolean;
    name: string;
    description: string;
    content: string;
    tag: string;
    role: "system" | "user" | "assistant";
    depth: number;
    selective: boolean;
    constant: boolean;
    position: number;
    order: number;
    scanDepth: number | null;
    excludeFromVectorization: boolean;
    lorebookId: string;
    secondaryKeys: string[];
    selectiveLogic: "and" | "and_all" | "or" | "not" | "not_all";
    probability: number | null;
    matchWholeWords: boolean;
    caseSensitive: boolean;
    useRegex: boolean;
    characterFilterMode: "any" | "include" | "exclude";
    characterFilterIds: string[];
    characterTagFilterMode: "any" | "include" | "exclude";
    characterTagFilters: string[];
    generationTriggerFilterMode: "any" | "include" | "exclude";
    generationTriggerFilters: string[];
    additionalMatchingSources: ("character_name" | "character_description" | "character_personality" | "character_scenario" | "character_tags" | "persona_description" | "persona_tags")[];
    sticky: number | null;
    cooldown: number | null;
    delay: number | null;
    ephemeral: number | null;
    group: string;
    groupWeight: number | null;
    folderId: string | null;
    preventRecursion: boolean;
    excludeRecursion: boolean;
    delayUntilRecursion: boolean;
    locked: boolean;
    relationships: Record<string, string>;
    dynamicState: Record<string, unknown>;
    activationConditions: {
        value: string;
        field: string;
        operator: "lt" | "equals" | "not_equals" | "contains" | "not_contains" | "gt";
    }[];
    schedule: {
        activeTimes: string[];
        activeDates: string[];
        activeLocations: string[];
    } | null;
}, {
    name: string;
    lorebookId: string;
    keys?: string[] | undefined;
    enabled?: boolean | undefined;
    description?: string | undefined;
    content?: string | undefined;
    tag?: string | undefined;
    role?: "system" | "user" | "assistant" | undefined;
    depth?: number | undefined;
    selective?: boolean | undefined;
    constant?: boolean | undefined;
    position?: number | undefined;
    order?: number | undefined;
    scanDepth?: number | null | undefined;
    excludeFromVectorization?: boolean | undefined;
    secondaryKeys?: string[] | undefined;
    selectiveLogic?: "and" | "and_all" | "or" | "not" | "not_all" | undefined;
    probability?: number | null | undefined;
    matchWholeWords?: boolean | undefined;
    caseSensitive?: boolean | undefined;
    useRegex?: boolean | undefined;
    characterFilterMode?: "any" | "include" | "exclude" | undefined;
    characterFilterIds?: string[] | undefined;
    characterTagFilterMode?: "any" | "include" | "exclude" | undefined;
    characterTagFilters?: string[] | undefined;
    generationTriggerFilterMode?: "any" | "include" | "exclude" | undefined;
    generationTriggerFilters?: string[] | undefined;
    additionalMatchingSources?: ("character_name" | "character_description" | "character_personality" | "character_scenario" | "character_tags" | "persona_description" | "persona_tags")[] | undefined;
    sticky?: number | null | undefined;
    cooldown?: number | null | undefined;
    delay?: number | null | undefined;
    ephemeral?: number | null | undefined;
    group?: string | undefined;
    groupWeight?: number | null | undefined;
    folderId?: string | null | undefined;
    preventRecursion?: boolean | undefined;
    excludeRecursion?: boolean | undefined;
    delayUntilRecursion?: boolean | undefined;
    locked?: boolean | undefined;
    relationships?: Record<string, string> | undefined;
    dynamicState?: Record<string, unknown> | undefined;
    activationConditions?: {
        value: string;
        field: string;
        operator: "lt" | "equals" | "not_equals" | "contains" | "not_contains" | "gt";
    }[] | undefined;
    schedule?: {
        activeTimes?: string[] | undefined;
        activeDates?: string[] | undefined;
        activeLocations?: string[] | undefined;
    } | null | undefined;
}>;
export declare const updateLorebookEntrySchema: z.ZodObject<{
    keys: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString, "many">>>;
    enabled: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    name: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodDefault<z.ZodString>>;
    content: z.ZodOptional<z.ZodDefault<z.ZodString>>;
    tag: z.ZodOptional<z.ZodDefault<z.ZodString>>;
    role: z.ZodOptional<z.ZodDefault<z.ZodEnum<["system", "user", "assistant"]>>>;
    depth: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    selective: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    constant: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    position: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    order: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    scanDepth: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodNumber>>>;
    excludeFromVectorization: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    secondaryKeys: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString, "many">>>;
    selectiveLogic: z.ZodOptional<z.ZodDefault<z.ZodEnum<["and", "and_all", "or", "not", "not_all"]>>>;
    probability: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodNumber>>>;
    matchWholeWords: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    caseSensitive: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    useRegex: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    characterFilterMode: z.ZodOptional<z.ZodDefault<z.ZodEnum<["any", "include", "exclude"]>>>;
    characterFilterIds: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString, "many">>>;
    characterTagFilterMode: z.ZodOptional<z.ZodDefault<z.ZodEnum<["any", "include", "exclude"]>>>;
    characterTagFilters: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString, "many">>>;
    generationTriggerFilterMode: z.ZodOptional<z.ZodDefault<z.ZodEnum<["any", "include", "exclude"]>>>;
    generationTriggerFilters: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString, "many">>>;
    additionalMatchingSources: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodEnum<["character_name", "character_description", "character_personality", "character_scenario", "character_tags", "persona_description", "persona_tags"]>, "many">>>;
    sticky: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodNumber>>>;
    cooldown: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodNumber>>>;
    delay: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodNumber>>>;
    ephemeral: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodNumber>>>;
    group: z.ZodOptional<z.ZodDefault<z.ZodString>>;
    groupWeight: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodNumber>>>;
    folderId: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodString>>>;
    preventRecursion: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    excludeRecursion: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    delayUntilRecursion: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    locked: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    relationships: z.ZodOptional<z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodString>>>;
    dynamicState: z.ZodOptional<z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>>;
    activationConditions: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodObject<{
        field: z.ZodString;
        operator: z.ZodEnum<["equals", "not_equals", "contains", "not_contains", "gt", "lt"]>;
        value: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        value: string;
        field: string;
        operator: "lt" | "equals" | "not_equals" | "contains" | "not_contains" | "gt";
    }, {
        value: string;
        field: string;
        operator: "lt" | "equals" | "not_equals" | "contains" | "not_contains" | "gt";
    }>, "many">>>;
    schedule: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodObject<{
        activeTimes: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        activeDates: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        activeLocations: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    }, "strip", z.ZodTypeAny, {
        activeTimes: string[];
        activeDates: string[];
        activeLocations: string[];
    }, {
        activeTimes?: string[] | undefined;
        activeDates?: string[] | undefined;
        activeLocations?: string[] | undefined;
    }>>>>;
}, "strip", z.ZodTypeAny, {
    keys?: string[] | undefined;
    enabled?: boolean | undefined;
    name?: string | undefined;
    description?: string | undefined;
    content?: string | undefined;
    tag?: string | undefined;
    role?: "system" | "user" | "assistant" | undefined;
    depth?: number | undefined;
    selective?: boolean | undefined;
    constant?: boolean | undefined;
    position?: number | undefined;
    order?: number | undefined;
    scanDepth?: number | null | undefined;
    excludeFromVectorization?: boolean | undefined;
    secondaryKeys?: string[] | undefined;
    selectiveLogic?: "and" | "and_all" | "or" | "not" | "not_all" | undefined;
    probability?: number | null | undefined;
    matchWholeWords?: boolean | undefined;
    caseSensitive?: boolean | undefined;
    useRegex?: boolean | undefined;
    characterFilterMode?: "any" | "include" | "exclude" | undefined;
    characterFilterIds?: string[] | undefined;
    characterTagFilterMode?: "any" | "include" | "exclude" | undefined;
    characterTagFilters?: string[] | undefined;
    generationTriggerFilterMode?: "any" | "include" | "exclude" | undefined;
    generationTriggerFilters?: string[] | undefined;
    additionalMatchingSources?: ("character_name" | "character_description" | "character_personality" | "character_scenario" | "character_tags" | "persona_description" | "persona_tags")[] | undefined;
    sticky?: number | null | undefined;
    cooldown?: number | null | undefined;
    delay?: number | null | undefined;
    ephemeral?: number | null | undefined;
    group?: string | undefined;
    groupWeight?: number | null | undefined;
    folderId?: string | null | undefined;
    preventRecursion?: boolean | undefined;
    excludeRecursion?: boolean | undefined;
    delayUntilRecursion?: boolean | undefined;
    locked?: boolean | undefined;
    relationships?: Record<string, string> | undefined;
    dynamicState?: Record<string, unknown> | undefined;
    activationConditions?: {
        value: string;
        field: string;
        operator: "lt" | "equals" | "not_equals" | "contains" | "not_contains" | "gt";
    }[] | undefined;
    schedule?: {
        activeTimes: string[];
        activeDates: string[];
        activeLocations: string[];
    } | null | undefined;
}, {
    keys?: string[] | undefined;
    enabled?: boolean | undefined;
    name?: string | undefined;
    description?: string | undefined;
    content?: string | undefined;
    tag?: string | undefined;
    role?: "system" | "user" | "assistant" | undefined;
    depth?: number | undefined;
    selective?: boolean | undefined;
    constant?: boolean | undefined;
    position?: number | undefined;
    order?: number | undefined;
    scanDepth?: number | null | undefined;
    excludeFromVectorization?: boolean | undefined;
    secondaryKeys?: string[] | undefined;
    selectiveLogic?: "and" | "and_all" | "or" | "not" | "not_all" | undefined;
    probability?: number | null | undefined;
    matchWholeWords?: boolean | undefined;
    caseSensitive?: boolean | undefined;
    useRegex?: boolean | undefined;
    characterFilterMode?: "any" | "include" | "exclude" | undefined;
    characterFilterIds?: string[] | undefined;
    characterTagFilterMode?: "any" | "include" | "exclude" | undefined;
    characterTagFilters?: string[] | undefined;
    generationTriggerFilterMode?: "any" | "include" | "exclude" | undefined;
    generationTriggerFilters?: string[] | undefined;
    additionalMatchingSources?: ("character_name" | "character_description" | "character_personality" | "character_scenario" | "character_tags" | "persona_description" | "persona_tags")[] | undefined;
    sticky?: number | null | undefined;
    cooldown?: number | null | undefined;
    delay?: number | null | undefined;
    ephemeral?: number | null | undefined;
    group?: string | undefined;
    groupWeight?: number | null | undefined;
    folderId?: string | null | undefined;
    preventRecursion?: boolean | undefined;
    excludeRecursion?: boolean | undefined;
    delayUntilRecursion?: boolean | undefined;
    locked?: boolean | undefined;
    relationships?: Record<string, string> | undefined;
    dynamicState?: Record<string, unknown> | undefined;
    activationConditions?: {
        value: string;
        field: string;
        operator: "lt" | "equals" | "not_equals" | "contains" | "not_contains" | "gt";
    }[] | undefined;
    schedule?: {
        activeTimes?: string[] | undefined;
        activeDates?: string[] | undefined;
        activeLocations?: string[] | undefined;
    } | null | undefined;
}>;
export declare const bulkUpdateLorebookEntriesSchema: z.ZodObject<{
    entryIds: z.ZodArray<z.ZodString, "many">;
    changes: z.ZodEffects<z.ZodObject<Pick<{
        keys: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString, "many">>>;
        enabled: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
        name: z.ZodOptional<z.ZodString>;
        description: z.ZodOptional<z.ZodDefault<z.ZodString>>;
        content: z.ZodOptional<z.ZodDefault<z.ZodString>>;
        tag: z.ZodOptional<z.ZodDefault<z.ZodString>>;
        role: z.ZodOptional<z.ZodDefault<z.ZodEnum<["system", "user", "assistant"]>>>;
        depth: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
        selective: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
        constant: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
        position: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
        order: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
        scanDepth: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodNumber>>>;
        excludeFromVectorization: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
        secondaryKeys: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString, "many">>>;
        selectiveLogic: z.ZodOptional<z.ZodDefault<z.ZodEnum<["and", "and_all", "or", "not", "not_all"]>>>;
        probability: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodNumber>>>;
        matchWholeWords: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
        caseSensitive: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
        useRegex: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
        characterFilterMode: z.ZodOptional<z.ZodDefault<z.ZodEnum<["any", "include", "exclude"]>>>;
        characterFilterIds: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString, "many">>>;
        characterTagFilterMode: z.ZodOptional<z.ZodDefault<z.ZodEnum<["any", "include", "exclude"]>>>;
        characterTagFilters: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString, "many">>>;
        generationTriggerFilterMode: z.ZodOptional<z.ZodDefault<z.ZodEnum<["any", "include", "exclude"]>>>;
        generationTriggerFilters: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString, "many">>>;
        additionalMatchingSources: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodEnum<["character_name", "character_description", "character_personality", "character_scenario", "character_tags", "persona_description", "persona_tags"]>, "many">>>;
        sticky: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodNumber>>>;
        cooldown: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodNumber>>>;
        delay: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodNumber>>>;
        ephemeral: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodNumber>>>;
        group: z.ZodOptional<z.ZodDefault<z.ZodString>>;
        groupWeight: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodNumber>>>;
        folderId: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodString>>>;
        preventRecursion: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
        excludeRecursion: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
        delayUntilRecursion: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
        locked: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
        relationships: z.ZodOptional<z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodString>>>;
        dynamicState: z.ZodOptional<z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>>;
        activationConditions: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodObject<{
            field: z.ZodString;
            operator: z.ZodEnum<["equals", "not_equals", "contains", "not_contains", "gt", "lt"]>;
            value: z.ZodString;
        }, "strip", z.ZodTypeAny, {
            value: string;
            field: string;
            operator: "lt" | "equals" | "not_equals" | "contains" | "not_contains" | "gt";
        }, {
            value: string;
            field: string;
            operator: "lt" | "equals" | "not_equals" | "contains" | "not_contains" | "gt";
        }>, "many">>>;
        schedule: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodObject<{
            activeTimes: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
            activeDates: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
            activeLocations: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        }, "strip", z.ZodTypeAny, {
            activeTimes: string[];
            activeDates: string[];
            activeLocations: string[];
        }, {
            activeTimes?: string[] | undefined;
            activeDates?: string[] | undefined;
            activeLocations?: string[] | undefined;
        }>>>>;
    }, "enabled" | "selective" | "constant" | "excludeFromVectorization" | "matchWholeWords" | "caseSensitive" | "useRegex" | "preventRecursion" | "excludeRecursion" | "delayUntilRecursion" | "locked">, "strip", z.ZodTypeAny, {
        enabled?: boolean | undefined;
        selective?: boolean | undefined;
        constant?: boolean | undefined;
        excludeFromVectorization?: boolean | undefined;
        matchWholeWords?: boolean | undefined;
        caseSensitive?: boolean | undefined;
        useRegex?: boolean | undefined;
        preventRecursion?: boolean | undefined;
        excludeRecursion?: boolean | undefined;
        delayUntilRecursion?: boolean | undefined;
        locked?: boolean | undefined;
    }, {
        enabled?: boolean | undefined;
        selective?: boolean | undefined;
        constant?: boolean | undefined;
        excludeFromVectorization?: boolean | undefined;
        matchWholeWords?: boolean | undefined;
        caseSensitive?: boolean | undefined;
        useRegex?: boolean | undefined;
        preventRecursion?: boolean | undefined;
        excludeRecursion?: boolean | undefined;
        delayUntilRecursion?: boolean | undefined;
        locked?: boolean | undefined;
    }>, {
        enabled?: boolean | undefined;
        selective?: boolean | undefined;
        constant?: boolean | undefined;
        excludeFromVectorization?: boolean | undefined;
        matchWholeWords?: boolean | undefined;
        caseSensitive?: boolean | undefined;
        useRegex?: boolean | undefined;
        preventRecursion?: boolean | undefined;
        excludeRecursion?: boolean | undefined;
        delayUntilRecursion?: boolean | undefined;
        locked?: boolean | undefined;
    }, {
        enabled?: boolean | undefined;
        selective?: boolean | undefined;
        constant?: boolean | undefined;
        excludeFromVectorization?: boolean | undefined;
        matchWholeWords?: boolean | undefined;
        caseSensitive?: boolean | undefined;
        useRegex?: boolean | undefined;
        preventRecursion?: boolean | undefined;
        excludeRecursion?: boolean | undefined;
        delayUntilRecursion?: boolean | undefined;
        locked?: boolean | undefined;
    }>;
}, "strip", z.ZodTypeAny, {
    entryIds: string[];
    changes: {
        enabled?: boolean | undefined;
        selective?: boolean | undefined;
        constant?: boolean | undefined;
        excludeFromVectorization?: boolean | undefined;
        matchWholeWords?: boolean | undefined;
        caseSensitive?: boolean | undefined;
        useRegex?: boolean | undefined;
        preventRecursion?: boolean | undefined;
        excludeRecursion?: boolean | undefined;
        delayUntilRecursion?: boolean | undefined;
        locked?: boolean | undefined;
    };
}, {
    entryIds: string[];
    changes: {
        enabled?: boolean | undefined;
        selective?: boolean | undefined;
        constant?: boolean | undefined;
        excludeFromVectorization?: boolean | undefined;
        matchWholeWords?: boolean | undefined;
        caseSensitive?: boolean | undefined;
        useRegex?: boolean | undefined;
        preventRecursion?: boolean | undefined;
        excludeRecursion?: boolean | undefined;
        delayUntilRecursion?: boolean | undefined;
        locked?: boolean | undefined;
    };
}>;
export type CreateLorebookInput = z.input<typeof createLorebookSchema>;
export type UpdateLorebookInput = z.infer<typeof updateLorebookSchema>;
export type CreateLorebookEntryInput = z.input<typeof createLorebookEntrySchema>;
export type UpdateLorebookEntryInput = z.infer<typeof updateLorebookEntrySchema>;
export type BulkUpdateLorebookEntriesInput = z.infer<typeof bulkUpdateLorebookEntriesSchema>;
export type CreateLorebookFolderInput = z.input<typeof createLorebookFolderSchema>;
export type UpdateLorebookFolderInput = z.infer<typeof updateLorebookFolderSchema>;
//# sourceMappingURL=lorebook.schema.d.ts.map