import { z } from "zod";
export declare const regexPlacementSchema: z.ZodEnum<["ai_output", "user_input"]>;
export declare const regexApplyModeSchema: z.ZodEnum<["prompt", "display", "both"]>;
export declare const createRegexScriptSchema: z.ZodEffects<z.ZodObject<{
    name: z.ZodString;
    enabled: z.ZodDefault<z.ZodBoolean>;
    findRegex: z.ZodEffects<z.ZodString, string, string>;
    replaceString: z.ZodDefault<z.ZodString>;
    trimStrings: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    placement: z.ZodArray<z.ZodEnum<["ai_output", "user_input"]>, "many">;
    flags: z.ZodEffects<z.ZodDefault<z.ZodString>, string, string | undefined>;
    promptOnly: z.ZodDefault<z.ZodBoolean>;
    applyMode: z.ZodOptional<z.ZodEnum<["prompt", "display", "both"]>>;
    targetCharacterIds: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    order: z.ZodOptional<z.ZodNumber>;
    minDepth: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
    maxDepth: z.ZodDefault<z.ZodNullable<z.ZodNumber>>;
}, "strip", z.ZodTypeAny, {
    enabled: boolean;
    name: string;
    placement: ("ai_output" | "user_input")[];
    findRegex: string;
    replaceString: string;
    trimStrings: string[];
    flags: string;
    promptOnly: boolean;
    targetCharacterIds: string[];
    minDepth: number | null;
    maxDepth: number | null;
    order?: number | undefined;
    applyMode?: "prompt" | "display" | "both" | undefined;
}, {
    name: string;
    placement: ("ai_output" | "user_input")[];
    findRegex: string;
    enabled?: boolean | undefined;
    order?: number | undefined;
    replaceString?: string | undefined;
    trimStrings?: string[] | undefined;
    flags?: string | undefined;
    promptOnly?: boolean | undefined;
    applyMode?: "prompt" | "display" | "both" | undefined;
    targetCharacterIds?: string[] | undefined;
    minDepth?: number | null | undefined;
    maxDepth?: number | null | undefined;
}>, {
    enabled: boolean;
    name: string;
    placement: ("ai_output" | "user_input")[];
    findRegex: string;
    replaceString: string;
    trimStrings: string[];
    flags: string;
    promptOnly: boolean;
    targetCharacterIds: string[];
    minDepth: number | null;
    maxDepth: number | null;
    order?: number | undefined;
    applyMode?: "prompt" | "display" | "both" | undefined;
}, {
    name: string;
    placement: ("ai_output" | "user_input")[];
    findRegex: string;
    enabled?: boolean | undefined;
    order?: number | undefined;
    replaceString?: string | undefined;
    trimStrings?: string[] | undefined;
    flags?: string | undefined;
    promptOnly?: boolean | undefined;
    applyMode?: "prompt" | "display" | "both" | undefined;
    targetCharacterIds?: string[] | undefined;
    minDepth?: number | null | undefined;
    maxDepth?: number | null | undefined;
}>;
export declare const updateRegexScriptSchema: z.ZodEffects<z.ZodObject<{
    name: z.ZodOptional<z.ZodString>;
    enabled: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    findRegex: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    replaceString: z.ZodOptional<z.ZodDefault<z.ZodString>>;
    trimStrings: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString, "many">>>;
    placement: z.ZodOptional<z.ZodArray<z.ZodEnum<["ai_output", "user_input"]>, "many">>;
    flags: z.ZodOptional<z.ZodEffects<z.ZodDefault<z.ZodString>, string, string | undefined>>;
    promptOnly: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    applyMode: z.ZodOptional<z.ZodOptional<z.ZodEnum<["prompt", "display", "both"]>>>;
    targetCharacterIds: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString, "many">>>;
    order: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    minDepth: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodNumber>>>;
    maxDepth: z.ZodOptional<z.ZodDefault<z.ZodNullable<z.ZodNumber>>>;
}, "strip", z.ZodTypeAny, {
    enabled?: boolean | undefined;
    name?: string | undefined;
    placement?: ("ai_output" | "user_input")[] | undefined;
    order?: number | undefined;
    findRegex?: string | undefined;
    replaceString?: string | undefined;
    trimStrings?: string[] | undefined;
    flags?: string | undefined;
    promptOnly?: boolean | undefined;
    applyMode?: "prompt" | "display" | "both" | undefined;
    targetCharacterIds?: string[] | undefined;
    minDepth?: number | null | undefined;
    maxDepth?: number | null | undefined;
}, {
    enabled?: boolean | undefined;
    name?: string | undefined;
    placement?: ("ai_output" | "user_input")[] | undefined;
    order?: number | undefined;
    findRegex?: string | undefined;
    replaceString?: string | undefined;
    trimStrings?: string[] | undefined;
    flags?: string | undefined;
    promptOnly?: boolean | undefined;
    applyMode?: "prompt" | "display" | "both" | undefined;
    targetCharacterIds?: string[] | undefined;
    minDepth?: number | null | undefined;
    maxDepth?: number | null | undefined;
}>, {
    enabled?: boolean | undefined;
    name?: string | undefined;
    placement?: ("ai_output" | "user_input")[] | undefined;
    order?: number | undefined;
    findRegex?: string | undefined;
    replaceString?: string | undefined;
    trimStrings?: string[] | undefined;
    flags?: string | undefined;
    promptOnly?: boolean | undefined;
    applyMode?: "prompt" | "display" | "both" | undefined;
    targetCharacterIds?: string[] | undefined;
    minDepth?: number | null | undefined;
    maxDepth?: number | null | undefined;
}, {
    enabled?: boolean | undefined;
    name?: string | undefined;
    placement?: ("ai_output" | "user_input")[] | undefined;
    order?: number | undefined;
    findRegex?: string | undefined;
    replaceString?: string | undefined;
    trimStrings?: string[] | undefined;
    flags?: string | undefined;
    promptOnly?: boolean | undefined;
    applyMode?: "prompt" | "display" | "both" | undefined;
    targetCharacterIds?: string[] | undefined;
    minDepth?: number | null | undefined;
    maxDepth?: number | null | undefined;
}>;
export declare const reorderRegexScriptsSchema: z.ZodObject<{
    scriptIds: z.ZodArray<z.ZodString, "many">;
}, "strip", z.ZodTypeAny, {
    scriptIds: string[];
}, {
    scriptIds: string[];
}>;
export type CreateRegexScriptInput = z.infer<typeof createRegexScriptSchema>;
export type UpdateRegexScriptInput = z.infer<typeof updateRegexScriptSchema>;
export type ReorderRegexScriptsInput = z.infer<typeof reorderRegexScriptsSchema>;
//# sourceMappingURL=regex.schema.d.ts.map